"use client";

import { Button } from "@/components/ui/button";
import { CountUp } from "@/components/count-up";
import type { ScanResult } from "@/lib/longevity";

const dateFormatter = new Intl.DateTimeFormat("en-US", {
  month: "long",
  year: "numeric",
});

function formatDelta(years: number): string {
  const rounded = Math.round(years * 10) / 10;
  return `${rounded >= 0 ? "+" : ""}${rounded.toFixed(1)} yr`;
}

export function ReportCard({
  result,
  onSeePlan,
}: {
  result: ScanResult;
  onSeePlan: () => void;
}) {
  const deathLabel = dateFormatter.format(result.predictedDeathDate);
  // Worst factors first so the biggest risks read at the top of the breakdown.
  const ordered = [...result.factors].sort((a, b) => a.deltaYears - b.deltaYears);

  return (
    <section className="mx-auto flex max-w-2xl flex-col gap-10 px-6 py-20">
      <div className="flex flex-col gap-2">
        <span className="font-mono text-xs uppercase tracking-[0.18em] text-monitor-alert">
          AI analysis complete
        </span>
        <h2 className="text-3xl font-semibold tracking-tight text-monitor-fg">
          Your estimated lifespan
        </h2>
        <p className="font-mono text-sm text-monitor-muted">
          Generated by our AI longevity model from your {result.factors.length}{" "}
          lifestyle markers.
        </p>
      </div>

      <div className="rounded-lg border border-monitor-alert/40 bg-monitor-panel p-8">
        <div className="font-mono text-xs uppercase tracking-[0.18em] text-monitor-muted">
          Estimated date of death
        </div>
        <div className="mt-2 font-mono text-5xl tracking-tighter text-monitor-alert md:text-6xl">
          {deathLabel}
        </div>
        <div className="mt-5 flex flex-wrap items-baseline gap-x-6 gap-y-2 font-mono text-sm text-monitor-fg">
          <span>
            Estimated lifespan{" "}
            <CountUp to={result.ageAtDeath} className="text-monitor-alert" /> years
          </span>
          <span className="text-monitor-muted">You are {result.currentAge} now</span>
          <span className="text-monitor-muted">Model confidence 94%</span>
        </div>
      </div>

      <div className="flex flex-col gap-3">
        <h3 className="font-mono text-xs uppercase tracking-[0.18em] text-monitor-muted">
          How the model reached this
        </h3>
        <ul className="flex flex-col divide-y divide-monitor-line">
          <li className="flex items-center justify-between gap-4 py-3">
            <span className="text-sm text-monitor-muted">
              National baseline life expectancy
            </span>
            <span className="shrink-0 font-mono text-sm text-monitor-muted">
              {result.baseLifeExpectancy.toFixed(1)} yr
            </span>
          </li>
          {ordered.map((factor) => {
            const positive = factor.deltaYears >= 0;
            return (
              <li key={factor.id} className="flex items-start justify-between gap-4 py-3">
                <div className="flex flex-col gap-1">
                  <span className="text-sm text-monitor-fg">
                    {factor.category}:{" "}
                    <span className="text-monitor-muted">{factor.answerLabel}</span>
                  </span>
                  <span className="text-xs leading-relaxed text-monitor-muted">
                    {factor.detail}
                  </span>
                </div>
                <span
                  className={`shrink-0 font-mono text-sm ${
                    positive ? "text-monitor-accent" : "text-monitor-alert"
                  }`}
                >
                  {formatDelta(factor.deltaYears)}
                </span>
              </li>
            );
          })}
          <li className="flex items-center justify-between gap-4 py-3">
            <span className="text-sm font-semibold text-monitor-fg">
              Your estimate
            </span>
            <span className="shrink-0 font-mono text-sm font-semibold text-monitor-fg">
              {result.lifeExpectancy.toFixed(1)} yr
            </span>
          </li>
        </ul>
      </div>

      {result.recoverableYears > 0 ? (
        <div className="rounded-lg border border-monitor-accent/40 bg-monitor-panel p-6">
          <p className="text-lg leading-relaxed text-monitor-fg">
            The model attributes{" "}
            <span className="font-mono text-monitor-accent">
              {result.recoverableYears.toFixed(1)} years
            </span>{" "}
            of that loss to habits you can still change. Reverse them and your
            projected date moves.
          </p>
          <Button
            onClick={onSeePlan}
            className="mt-4 bg-monitor-accent text-monitor-bg hover:bg-monitor-accent/90"
          >
            Show me how to reclaim them
          </Button>
        </div>
      ) : (
        <div className="rounded-lg border border-monitor-accent/40 bg-monitor-panel p-6">
          <p className="text-lg leading-relaxed text-monitor-fg">
            Your modifiable risks are already low. The protocol can help you push
            toward the upper bound of your range.
          </p>
          <Button
            onClick={onSeePlan}
            className="mt-4 bg-monitor-accent text-monitor-bg hover:bg-monitor-accent/90"
          >
            See the protocol
          </Button>
        </div>
      )}
    </section>
  );
}
