// Fixed recipe library for the deterministic guide engine.
// All macros are ESTIMATES per serving. No em-dashes anywhere in this file.
// Tags drive selection in buildRecipeBank: goal, diet, and vegetarian filtering.

import type { Recipe } from "@/lib/guide/schema";

export const RECIPES: Recipe[] = [
  // ─── Breakfast ───────────────────────────────────────────────────────────────

  {
    id: "b01",
    name: "Scrambled eggs with spinach and feta",
    meal: "breakfast",
    tags: ["high-protein", "quick", "vegetarian", "low-cal"],
    servings: 1,
    timeMins: 10,
    calories: 320,
    proteinG: 26,
    ingredients: [
      "3 large eggs",
      "30 g feta cheese, crumbled",
      "1 large handful of baby spinach (about 40 g)",
      "1 teaspoon olive oil",
      "Salt and black pepper to taste",
    ],
    steps: [
      "Crack the eggs into a bowl, season with a pinch of salt and pepper, and beat lightly with a fork.",
      "Heat the olive oil in a non-stick pan over medium-low heat.",
      "Add the spinach and stir for about 30 seconds until it just wilts.",
      "Pour in the eggs and stir gently with a spatula every few seconds.",
      "When the eggs are mostly set but still slightly glossy, remove from heat and scatter over the feta.",
      "Serve immediately.",
    ],
    note: "Estimates: 320 kcal, 26 g protein per serving.",
  },
  {
    id: "b02",
    name: "Greek yogurt protein bowl",
    meal: "breakfast",
    tags: ["high-protein", "quick", "vegetarian", "balanced"],
    servings: 1,
    timeMins: 5,
    calories: 360,
    proteinG: 30,
    ingredients: [
      "200 g full-fat Greek yogurt",
      "1 scoop (25 g) vanilla or unflavoured protein powder (optional - omit if not using)",
      "1 small banana, sliced, or 80 g mixed berries",
      "1 tablespoon pumpkin seeds or mixed nuts",
      "1 teaspoon honey",
    ],
    steps: [
      "Spoon the Greek yogurt into a bowl.",
      "If using protein powder, stir it in until fully mixed.",
      "Top with the banana or berries.",
      "Scatter over the seeds or nuts and drizzle with honey.",
    ],
    note: "Estimates: 360 kcal, 30 g protein per serving. Protein powder adds about 20 g extra protein.",
  },
  {
    id: "b03",
    name: "Overnight oats with chia and berries",
    meal: "breakfast",
    tags: ["higher-carb", "vegetarian", "plant-protein", "balanced"],
    servings: 1,
    timeMins: 5,
    calories: 420,
    proteinG: 20,
    ingredients: [
      "80 g rolled oats (not instant)",
      "200 ml skim or unsweetened oat milk",
      "2 tablespoons chia seeds",
      "100 g low-fat Greek yogurt",
      "80 g mixed berries, fresh or frozen",
      "1 teaspoon honey or maple syrup",
    ],
    steps: [
      "Combine the oats, chia seeds, and milk in a jar or container. Stir well.",
      "Cover and refrigerate overnight (at least 6 hours).",
      "In the morning, stir and add a splash of extra milk if the mixture is too thick.",
      "Top with the Greek yogurt, berries, and a drizzle of honey.",
    ],
    note: "Estimates: 420 kcal, 20 g protein per serving. Prep the night before for a grab-and-go breakfast.",
  },
  {
    id: "b04",
    name: "Egg white and oat pancakes",
    meal: "breakfast",
    tags: ["high-protein", "higher-carb", "low-cal", "quick"],
    servings: 2,
    timeMins: 15,
    calories: 140,
    proteinG: 14,
    ingredients: [
      "4 egg whites (or 120 ml carton egg whites)",
      "1 whole egg",
      "60 g rolled oats",
      "1 teaspoon baking powder",
      "1 teaspoon vanilla extract",
      "Pinch of salt",
      "1 teaspoon coconut or vegetable oil for frying",
      "Fresh berries or sliced banana to serve",
    ],
    steps: [
      "Blend or blitz the oats in a blender until they look like rough flour.",
      "Add the egg whites, whole egg, baking powder, vanilla, and salt. Blend until smooth.",
      "Heat a non-stick pan over medium heat and brush with a little oil.",
      "Pour small rounds of batter (about 3 inches across) and cook for 2 to 3 minutes until bubbles appear on the surface.",
      "Flip and cook for another 1 to 2 minutes until golden.",
      "Serve topped with fresh berries or banana.",
    ],
    note: "Estimates: 140 kcal, 14 g protein per serving. Makes about 6 small pancakes (3 per serving).",
  },
  {
    id: "b05",
    name: "Smoked salmon and avocado on rye",
    meal: "breakfast",
    tags: ["high-protein", "balanced", "quick"],
    servings: 1,
    timeMins: 5,
    calories: 390,
    proteinG: 27,
    ingredients: [
      "2 slices rye bread or dark whole-grain bread",
      "100 g smoked salmon",
      "Half a ripe avocado, sliced",
      "1 teaspoon capers (optional)",
      "Juice of half a lemon",
      "Black pepper to taste",
    ],
    steps: [
      "Toast the rye bread.",
      "Arrange the avocado slices on the toast and squeeze over the lemon juice.",
      "Lay the smoked salmon on top.",
      "Add capers if using and finish with black pepper.",
    ],
    note: "Estimates: 390 kcal, 27 g protein per serving.",
  },

  // ─── Lunch ────────────────────────────────────────────────────────────────────

  {
    id: "l01",
    name: "Chicken and quinoa power bowl",
    meal: "lunch",
    tags: ["high-protein", "higher-carb", "balanced"],
    servings: 1,
    timeMins: 20,
    calories: 480,
    proteinG: 42,
    ingredients: [
      "150 g boneless, skinless chicken breast",
      "70 g uncooked quinoa (or 140 g pre-cooked)",
      "1 large handful of arugula or mixed greens",
      "8 cherry tomatoes, halved",
      "Half a cucumber, sliced",
      "1 tablespoon olive oil",
      "Juice of half a lemon",
      "Salt, pepper, and a pinch of garlic powder",
    ],
    steps: [
      "Cook the quinoa according to packet instructions (usually 12 minutes in simmering water). Drain and cool.",
      "Season the chicken with salt, pepper, and garlic powder.",
      "Heat a pan over medium-high heat with a little oil and cook the chicken for 5 to 6 minutes per side until cooked through. Rest for 2 minutes, then slice.",
      "Toss the leaves, tomatoes, and cucumber with olive oil and lemon juice.",
      "Assemble the bowl: greens at the base, quinoa on one side, sliced chicken on the other.",
    ],
    note: "Estimates: 480 kcal, 42 g protein per serving.",
  },
  {
    id: "l02",
    name: "Canned tuna and white bean salad",
    meal: "lunch",
    tags: ["high-protein", "quick", "low-cal", "balanced"],
    servings: 1,
    timeMins: 8,
    calories: 380,
    proteinG: 38,
    ingredients: [
      "1 tin (120 g drained) tuna in spring water",
      "200 g canned white beans (cannellini or haricot), drained and rinsed",
      "2 sticks of celery, finely sliced",
      "Half a small red onion, finely diced",
      "8 cherry tomatoes, halved",
      "1 tablespoon olive oil",
      "1 tablespoon red wine vinegar",
      "Salt, pepper, and a pinch of dried oregano",
    ],
    steps: [
      "Drain the tuna and flake it into a bowl.",
      "Add the beans, celery, red onion, and tomatoes.",
      "Drizzle over the olive oil and vinegar, then season with salt, pepper, and oregano.",
      "Toss everything together and serve at room temperature.",
    ],
    note: "Estimates: 380 kcal, 38 g protein per serving. Keeps in the fridge for up to 2 days.",
  },
  {
    id: "l03",
    name: "Lentil and vegetable soup",
    meal: "lunch",
    tags: ["plant-protein", "vegetarian", "low-cal", "balanced", "higher-carb"],
    servings: 3,
    timeMins: 30,
    calories: 290,
    proteinG: 18,
    ingredients: [
      "200 g red lentils, rinsed",
      "1 medium onion, diced",
      "2 medium carrots, diced",
      "2 sticks of celery, diced",
      "2 garlic cloves, minced",
      "400 g canned chopped tomatoes",
      "1 quart vegetable stock (low-sodium)",
      "1 teaspoon ground cumin",
      "1 teaspoon smoked paprika",
      "1 tablespoon olive oil",
      "Salt and pepper to taste",
    ],
    steps: [
      "Heat the olive oil in a large pot over medium heat. Add the onion, carrots, and celery and cook for 5 minutes, stirring occasionally.",
      "Add the garlic, cumin, and paprika and stir for 1 minute.",
      "Add the lentils, canned tomatoes, and stock. Bring to a boil.",
      "Reduce heat and simmer for 20 minutes until the lentils are completely soft.",
      "Season with salt and pepper. Blend a quarter of the soup with a stick blender for a thicker texture, if you like.",
    ],
    note: "Estimates: 290 kcal, 18 g protein per serving. Makes 3 servings. Freezes well.",
  },
  {
    id: "l04",
    name: "Turkey and avocado wrap",
    meal: "lunch",
    tags: ["high-protein", "quick", "balanced"],
    servings: 1,
    timeMins: 8,
    calories: 440,
    proteinG: 38,
    ingredients: [
      "1 large whole-wheat or seeded wrap",
      "120 g cooked sliced turkey breast",
      "Half a ripe avocado, mashed",
      "2 large romaine lettuce leaves",
      "4 slices of tomato",
      "1 teaspoon Dijon mustard",
      "Salt and black pepper",
    ],
    steps: [
      "Spread the mashed avocado over the wrap, then add a thin layer of Dijon mustard.",
      "Layer the lettuce leaves and tomato slices down the center.",
      "Add the turkey breast and season with salt and pepper.",
      "Fold in the sides and roll the wrap tightly. Cut in half to serve.",
    ],
    note: "Estimates: 440 kcal, 38 g protein per serving.",
  },
  {
    id: "l05",
    name: "Tofu and edamame stir-fry bowl",
    meal: "lunch",
    tags: ["plant-protein", "vegetarian", "balanced", "higher-carb"],
    servings: 2,
    timeMins: 20,
    calories: 420,
    proteinG: 28,
    ingredients: [
      "300 g firm tofu, drained and pressed",
      "150 g frozen shelled edamame, defrosted",
      "200 g pre-cooked brown rice (1 pouch)",
      "1 medium red pepper, sliced",
      "1 medium zucchini, sliced into half-moons",
      "2 tablespoons low-sodium soy sauce or tamari",
      "1 tablespoon sesame oil",
      "1 garlic clove, minced",
      "1 teaspoon fresh or ground ginger",
      "1 teaspoon sesame seeds to garnish",
    ],
    steps: [
      "Cut the tofu into 3/4-inch cubes. Pat dry with paper towels.",
      "Heat the sesame oil in a large pan or wok over high heat. Add the tofu and fry for 3 to 4 minutes per side until golden. Remove and set aside.",
      "In the same pan, add the pepper and zucchini and stir-fry for 3 minutes.",
      "Add the garlic and ginger and cook for 30 seconds.",
      "Add the edamame, rice, and soy sauce. Toss to combine and heat through for 2 minutes.",
      "Return the tofu to the pan, toss everything together, and garnish with sesame seeds.",
    ],
    note: "Estimates: 420 kcal, 28 g protein per serving. Makes 2 servings.",
  },

  // ─── Dinner ───────────────────────────────────────────────────────────────────

  {
    id: "d01",
    name: "Baked lemon herb salmon with roasted vegetables",
    meal: "dinner",
    tags: ["high-protein", "low-cal", "balanced"],
    servings: 2,
    timeMins: 30,
    calories: 430,
    proteinG: 40,
    ingredients: [
      "2 salmon fillets (about 150 g each)",
      "1 medium zucchini, sliced",
      "1 medium red pepper, cut into chunks",
      "1 head of broccoli, broken into florets",
      "2 tablespoons olive oil",
      "Juice and zest of 1 lemon",
      "2 garlic cloves, minced",
      "1 teaspoon dried mixed herbs or Italian seasoning",
      "Salt and black pepper",
    ],
    steps: [
      "Preheat the oven to 400 F (200 C).",
      "Toss the vegetables in 1 tablespoon of olive oil, season, and spread on a baking tray.",
      "Roast the vegetables for 10 minutes.",
      "Place the salmon fillets on top of or alongside the vegetables. Drizzle with the remaining oil, lemon juice and zest, garlic, and herbs.",
      "Return to the oven for 15 minutes, or until the salmon is just cooked through and flakes easily.",
    ],
    note: "Estimates: 430 kcal, 40 g protein per serving. Makes 2 servings.",
  },
  {
    id: "d02",
    name: "Beef and broccoli with rice",
    meal: "dinner",
    tags: ["high-protein", "higher-carb", "balanced"],
    servings: 2,
    timeMins: 25,
    calories: 520,
    proteinG: 44,
    ingredients: [
      "300 g lean beef sirloin or rump, thinly sliced against the grain",
      "1 large head of broccoli, cut into small florets",
      "200 g pre-cooked brown or white rice (1 pouch)",
      "2 tablespoons low-sodium soy sauce or tamari",
      "1 tablespoon oyster sauce",
      "1 teaspoon cornflour",
      "1 tablespoon sesame oil",
      "2 garlic cloves, minced",
      "1 teaspoon fresh or ground ginger",
    ],
    steps: [
      "Mix the beef with the soy sauce, cornflour, and half the sesame oil. Let it sit for 5 minutes.",
      "Blanch the broccoli florets in boiling water for 2 minutes, then drain.",
      "Heat a large pan or wok over very high heat. Add the beef in a single layer and sear for 1 to 2 minutes per side. Remove and set aside.",
      "In the same pan, add the remaining oil, garlic, and ginger. Stir for 30 seconds.",
      "Add the broccoli and toss for 2 minutes. Return the beef and add the oyster sauce.",
      "Toss everything together and serve over the rice.",
    ],
    note: "Estimates: 520 kcal, 44 g protein per serving. Makes 2 servings.",
  },
  {
    id: "d03",
    name: "Chicken and chickpea one-pan bake",
    meal: "dinner",
    tags: ["high-protein", "balanced", "higher-carb"],
    servings: 2,
    timeMins: 35,
    calories: 490,
    proteinG: 46,
    ingredients: [
      "2 bone-in chicken thighs (skin removed) or 300 g boneless thighs",
      "400 g tin chickpeas, drained and rinsed",
      "400 g tin chopped tomatoes",
      "1 medium red onion, cut into wedges",
      "1 red pepper, cut into chunks",
      "2 teaspoons smoked paprika",
      "1 teaspoon ground cumin",
      "2 garlic cloves, sliced",
      "1 tablespoon olive oil",
      "Salt and pepper",
      "Fresh parsley or cilantro to garnish",
    ],
    steps: [
      "Preheat the oven to 375 F (190 C).",
      "In a large oven-safe dish or roasting tray, combine the chickpeas, tomatoes, onion, pepper, garlic, spices, and olive oil. Season and stir to mix.",
      "Nestle the chicken thighs on top and season the chicken.",
      "Roast for 30 to 35 minutes, until the chicken is cooked through (juices run clear).",
      "Scatter over the parsley or cilantro before serving.",
    ],
    note: "Estimates: 490 kcal, 46 g protein per serving. Makes 2 servings. Works well with a side of crusty bread to soak up the sauce.",
  },
  {
    id: "d04",
    name: "Black bean and sweet potato tacos",
    meal: "dinner",
    tags: ["plant-protein", "vegetarian", "balanced", "higher-carb"],
    servings: 2,
    timeMins: 30,
    calories: 440,
    proteinG: 18,
    ingredients: [
      "1 large sweet potato (about 300 g), peeled and diced",
      "400 g tin black beans, drained and rinsed",
      "4 to 6 small corn or flour tortillas",
      "1 teaspoon ground cumin",
      "1 teaspoon smoked paprika",
      "1 tablespoon olive oil",
      "1 lime, cut into wedges",
      "4 tablespoons plain Greek yogurt (as a sour cream alternative)",
      "1 small avocado, mashed",
      "Fresh salsa or 4 tablespoons chopped tomato with cilantro",
      "Salt and pepper",
    ],
    steps: [
      "Preheat the oven to 400 F (200 C). Toss the sweet potato in oil, cumin, paprika, salt, and pepper.",
      "Roast for 20 to 25 minutes until tender and slightly caramelized at the edges.",
      "Warm the black beans in a small pan with a pinch of cumin and salt for 2 minutes.",
      "Warm the tortillas in a dry pan for 30 seconds per side.",
      "Build each taco: a spoonful of beans and sweet potato, a dollop of mashed avocado, a small spoon of Greek yogurt, and some salsa.",
      "Serve with lime wedges on the side.",
    ],
    note: "Estimates: 440 kcal, 18 g protein per serving. Makes 2 servings (2 to 3 tacos each).",
  },
  {
    id: "d05",
    name: "Lean ground beef and vegetable bowl",
    meal: "dinner",
    tags: ["high-protein", "low-cal", "balanced"],
    servings: 2,
    timeMins: 20,
    calories: 400,
    proteinG: 42,
    ingredients: [
      "300 g extra-lean ground beef (95 percent lean or higher)",
      "1 medium onion, diced",
      "1 zucchini, diced",
      "1 red pepper, diced",
      "400 g tin chopped tomatoes",
      "1 garlic clove, minced",
      "1 teaspoon Italian mixed herbs",
      "1 teaspoon olive oil",
      "Salt and pepper",
      "Handful of baby spinach to stir in at the end",
    ],
    steps: [
      "Heat the olive oil in a large pan over medium-high heat. Add the onion and cook for 3 minutes.",
      "Add the ground beef and break it up with a spoon. Cook until browned all over, about 5 minutes.",
      "Add the garlic, zucchini, and pepper. Stir and cook for 3 minutes.",
      "Pour in the canned tomatoes and add the herbs. Season with salt and pepper.",
      "Simmer for 10 minutes, then stir in the baby spinach until wilted.",
      "Serve on its own, over rice, or in a wrap.",
    ],
    note: "Estimates: 400 kcal, 42 g protein per serving. Makes 2 servings.",
  },
  {
    id: "d06",
    name: "Baked cod with lentils and greens",
    meal: "dinner",
    tags: ["high-protein", "low-cal", "balanced"],
    servings: 2,
    timeMins: 25,
    calories: 370,
    proteinG: 40,
    ingredients: [
      "2 cod fillets (about 150 g each)",
      "400 g tin green or Puy lentils, drained and rinsed",
      "200 g kale or savoy cabbage, roughly chopped",
      "1 medium onion, diced",
      "2 garlic cloves, minced",
      "1 tablespoon olive oil",
      "Juice of 1 lemon",
      "1 teaspoon smoked paprika",
      "Salt and pepper",
    ],
    steps: [
      "Preheat the oven to 375 F (190 C).",
      "Place the cod on a baking tray lined with foil. Season with salt, pepper, and paprika, and squeeze over half the lemon juice.",
      "Bake for 15 to 18 minutes until the fish flakes easily.",
      "Meanwhile, heat the olive oil in a pan. Cook the onion for 4 minutes, then add the garlic for 30 seconds.",
      "Add the lentils and kale. Stir over medium heat for 3 to 4 minutes until the kale wilts and everything is warmed through. Season and add the remaining lemon juice.",
      "Serve the lentil and greens base with the cod on top.",
    ],
    note: "Estimates: 370 kcal, 40 g protein per serving. Makes 2 servings.",
  },
  {
    id: "d07",
    name: "Prawn and vegetable fried cauliflower rice",
    meal: "dinner",
    tags: ["high-protein", "low-cal", "quick"],
    servings: 2,
    timeMins: 15,
    calories: 300,
    proteinG: 34,
    ingredients: [
      "300 g raw prawns, peeled (or frozen, defrosted)",
      "400 g pre-riced cauliflower (fresh or frozen)",
      "150 g frozen peas",
      "2 eggs, beaten",
      "2 green onions, sliced",
      "2 tablespoons low-sodium soy sauce",
      "1 tablespoon sesame oil",
      "1 garlic clove, minced",
      "1 teaspoon fresh or ground ginger",
    ],
    steps: [
      "Heat the sesame oil in a large pan or wok over high heat. Add the garlic and ginger and stir for 30 seconds.",
      "Add the prawns and cook for 2 minutes until pink. Push to one side.",
      "Add the cauliflower rice and frozen peas. Stir-fry for 3 minutes.",
      "Push everything to the sides and pour the beaten eggs into the center. Scramble for 1 minute, then fold into the rice.",
      "Add the soy sauce and green onions, toss everything together, and serve immediately.",
    ],
    note: "Estimates: 300 kcal, 34 g protein per serving. Makes 2 servings.",
  },

  // ─── Snacks ───────────────────────────────────────────────────────────────────

  {
    id: "s01",
    name: "Cottage cheese with pineapple and seeds",
    meal: "snack",
    tags: ["high-protein", "low-cal", "quick", "vegetarian"],
    servings: 1,
    timeMins: 3,
    calories: 190,
    proteinG: 22,
    ingredients: [
      "150 g low-fat cottage cheese",
      "80 g canned pineapple chunks in juice (drained), or fresh pineapple",
      "1 tablespoon pumpkin seeds",
    ],
    steps: [
      "Spoon the cottage cheese into a bowl.",
      "Top with the pineapple and scatter over the seeds.",
    ],
    note: "Estimates: 190 kcal, 22 g protein per serving.",
  },
  {
    id: "s02",
    name: "Hard-boiled eggs with rice cakes",
    meal: "snack",
    tags: ["high-protein", "quick", "vegetarian", "low-cal", "balanced"],
    servings: 1,
    timeMins: 12,
    calories: 210,
    proteinG: 18,
    ingredients: [
      "2 large eggs",
      "2 plain rice cakes",
      "Salt and black pepper",
      "Optional: a pinch of smoked paprika",
    ],
    steps: [
      "Place eggs in a pot of cold water. Bring to a boil, then cook for 7 minutes.",
      "Transfer to cold water for 2 minutes, then peel.",
      "Slice or eat whole alongside the rice cakes.",
      "Season with salt, pepper, and paprika if using.",
    ],
    note: "Estimates: 210 kcal, 18 g protein per serving. Cook eggs in bulk at the start of the week.",
  },
  {
    id: "s03",
    name: "Edamame with sea salt",
    meal: "snack",
    tags: ["plant-protein", "vegetarian", "quick", "low-cal", "high-protein"],
    servings: 1,
    timeMins: 5,
    calories: 150,
    proteinG: 14,
    ingredients: [
      "150 g frozen edamame in pods (or shelled)",
      "Pinch of sea salt or soy sauce for dipping",
    ],
    steps: [
      "Cook the edamame according to packet instructions (usually 3 to 4 minutes in boiling water or 3 minutes in the microwave).",
      "Drain and toss with a pinch of sea salt, or dip individual pods in a little soy sauce.",
    ],
    note: "Estimates: 150 kcal, 14 g protein per serving.",
  },
  {
    id: "s04",
    name: "Apple with almond butter",
    meal: "snack",
    tags: ["quick", "vegetarian", "balanced", "plant-protein"],
    servings: 1,
    timeMins: 2,
    calories: 220,
    proteinG: 6,
    ingredients: [
      "1 medium apple",
      "2 tablespoons almond butter (about 30 g)",
    ],
    steps: [
      "Core and slice the apple into wedges.",
      "Serve alongside the almond butter for dipping.",
    ],
    note: "Estimates: 220 kcal, 6 g protein per serving. Simple and portable.",
  },
  {
    id: "s05",
    name: "Sardines on oatcakes",
    meal: "snack",
    tags: ["high-protein", "quick", "balanced", "low-cal"],
    servings: 1,
    timeMins: 3,
    calories: 240,
    proteinG: 20,
    ingredients: [
      "1 tin (90 g drained) sardines in olive oil or brine",
      "3 oatcakes",
      "Squeeze of lemon juice",
      "Black pepper",
    ],
    steps: [
      "Drain the sardines. Break them up gently with a fork.",
      "Spoon onto the oatcakes. Add a squeeze of lemon and black pepper.",
    ],
    note: "Estimates: 240 kcal, 20 g protein per serving. Canned sardines are one of the most affordable and nutritious protein sources available.",
  },
];
