import { z } from "zod";

// The AI Deepscan output shape. Generated by Claude Haiku when an API key is
// configured, by the deterministic offline builder otherwise. Either way the
// result is validated against this schema before it is stored or rendered.

export const DeepscanMarkerSchema = z.object({
  name: z.string().min(1),
  /** The user's self-reported band, e.g. "60 to 70 bpm". */
  band: z.string().min(1),
  status: z.enum(["optimal", "watch", "flag"]),
  note: z.string().min(1),
});

export const DeepscanSectionSchema = z.object({
  title: z.string().min(1),
  body: z.string().min(1),
  /** Concrete, do-this actions for the section. The "actionable" payload. */
  actions: z.array(z.string().min(1)).min(1),
});

export const DeepscanReportSchema = z.object({
  /** 2-4 sentence overall readout, addressed to the reader. */
  summary: z.string().min(1),
  /** Marker-by-marker table: at least 8 rows. */
  markers: z.array(DeepscanMarkerSchema).min(8),
  /** Narrative sections (body, cardiometabolic, fueling, recovery, stress, movement, hormones). */
  sections: z.array(DeepscanSectionSchema).min(5),
  /** Ordered "fix these first" list. */
  priorities: z.array(z.string().min(1)).min(3),
  /** Always rendered: estimates from self-reported answers, not diagnostics. */
  disclaimer: z.string().min(1),
});

// What gets stored on the order: the report plus the deep answers that
// produced it and provenance (model + timestamp). One run per purchase.
export const DeepscanRecordSchema = z.object({
  report: DeepscanReportSchema,
  answers: z.record(
    z.string().max(40),
    z.union([z.string().max(80), z.array(z.string().max(80)).max(10)])
  ),
  model: z.string().min(1),
  generatedAt: z.string().min(1),
});

export type DeepscanMarker = z.infer<typeof DeepscanMarkerSchema>;
export type DeepscanSection = z.infer<typeof DeepscanSectionSchema>;
export type DeepscanReport = z.infer<typeof DeepscanReportSchema>;
export type DeepscanRecord = z.infer<typeof DeepscanRecordSchema>;

/** Answer map for the deepscan intake (string or string[] only, no numbers). */
export type DeepscanAnswers = z.infer<typeof DeepscanRecordSchema>["answers"];
